### Stage 1: build
FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/package*.json frontend/tsconfig*.json ./
COPY frontend/ ./
RUN npm install --silent
RUN npm run build

### Stage 2: serve
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
